nfs-iostat: divide by zero with fresh mount
When an export is freshly mounted, /proc/self/mountstats displays age = 0.
This causes nfs-iostat to divide by zero throwing an error.
When we have age = 0, other stats are greater than 0, so we'll set age = 1 and
print the relevant stats.

This will prevent a backtrace like this from occurring if nfsiostat is run.

nfsiostat -s 1
Traceback (most recent call last):
  File "/usr/sbin/nfsiostat", line 662, in <module>
    iostat_command(prog)
  File "/usr/sbin/nfsiostat", line 644, in iostat_command
    print_iostat_summary(old_mountstats, mountstats, devices, sample_time, options)
  File "/usr/sbin/nfsiostat", line 490, in print_iostat_summary
    devicelist.sort(key=lambda x: stats[x].ops(time), reverse=True)
  File "/usr/sbin/nfsiostat", line 490, in <lambda>
    devicelist.sort(key=lambda x: stats[x].ops(time), reverse=True)
  File "/usr/sbin/nfsiostat", line 383, in ops
    return (sends / sample_time)
ZeroDivisionError: float division by zero

Signed-off-by: Kenneth D'souza <kdsouza@redhat.com>
Signed-off-by: Steve Dickson <steved@redhat.com>