Removed ISO C does not support the '%m' gnu_printf format errors
nfsstat.c: In function 'mounts':
nfsstat.c:1016:3: error: ISO C does not support the '%m' gnu_printf
format [-Werror=format=]
   fprintf(stderr, "Warning: %s: %m\n", name);
   ^
nfsstat.c: In function 'get_stats':
nfsstat.c:1093:6: error: ISO C does not support the '%m' gnu_printf
format [-Werror=format=]
      label, file);

statd.c: In function 'set_nlm_port':
statd.c:235:5: error: ISO C does not support the '%m' gnu_printf format
[-Werror=format=]
     name_p, type);
     ^
statd.c:238:3: error: ISO C does not support the '%m' gnu_printf format
[-Werror=format=]
   fprintf(stderr, "%s: failed to open %s: %m\n", name_p, pathbuf);

Signed-off-by: Steve Dickson <steved@redhat.com>