make_timestamp: removed a -Werror=unused-result error
conffile.c:1440:3: error: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Werror=unused-result]
   asprintf(&tmpstr, "%s on %s", modified_by, datestr);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Steve Dickson <steved@redhat.com>